rm(list = ls())
# install.packages("Jmisc")
library(Jmisc)

target.dir <- "~/Human_brain_research/Mixture_models/Log_normal_mixture_model/Grid_Search"
setwd(target.dir)
source("../../../Mixture_models/compute_log_likelihood_for_normal.R")
source("../../../Data/Full_Data/read_data_from_excel_file.R")
sourceAll(paste(target.dir,"llk_computation",sep = "/"))
sourceAll(paste(target.dir,"log_normal_grid_search/",sep = "/"))
sourceAll(paste(target.dir,"compute_parameters",sep = "/"))
sourceAll(paste(target.dir,"log_normal_grid_search",sep = "/"))
sourceAll(paste(target.dir,"visualization_methods/",sep = "/"))
sourceAll("../data_processing_methods/")
source(paste(target.dir,"run_grid_search_analysis_over_log_normal_data.R", sep = "/"))
# source(paste(target.dir,"tests/testing_log_normal_grid_search.R", sep = "/"))