library(Jmisc)
sourceAll("~/Human_brain_research/Mixture_models/EM/Estep/")
sourceAll("~/Human_brain_research/Mixture_models/EM/Mstep/")
sourceAll("~/Human_brain_research/Mixture_models/EM/EM/")
source("~/Human_brain_research/Mixture_models/EM/EM_Class/source_EM_class.R")
source("~/Human_brain_research/Mixture_models/compute_log_likelihood_for_normal.R")
source("~/Human_brain_research/Mixture_models/EM/main_function_for_gender_mixture_model.R")
