---
title: "Factor Analysis"
author: "Nitay Alon"
date: "May 17, 2019"
output: html_document
---

In this report we perform factor analysis over standardized residuals to examine the latent structure. The first analysis in conducted on the residuals themselves followed by an analysis of the responsibilities.  
```{r loading environmet, include=FALSE, warning=FALSE}
library(pbapply)
local_server_prefix <- "~/Human_brain_research/"
source(paste0(local_server_prefix,"BioBank_data_analysis/New_Analysis_Method/Residuals_analysis_methods/analyze_full_brain_feature.R"))
source(paste0(local_server_prefix,"BioBank_data_analysis/New_Analysis_Method/Residuals_analysis_methods/method_helper.R"))
source(paste0(local_server_prefix,"BioBank_data_analysis/load_biobank_data.R"))
load("~/Human_brain_research/BioBank_data_analysis/BioBank_data_analysis_total.RData")
load("~/Human_brain_research/BioBank_data_analysis/New_Analysis_Method/Residuals_analysis_methods/Results/combined_df_long_sorted.RData")
```

## Residuals
```{r residuals factor analysis by gender, include=FALSE}
sig_level <- 0.01
FDR_significant_features <- rownames(combined_df_long_sorted)[
    with(combined_df_long_sorted,(fdr_pv <= sig_level & p < 0.5 & q > 0.5 |
                                  fdr_pv <= sig_level & p > 0.5 & q < 0.5))]  
FDR_significant_features <- na.omit(FDR_significant_features)

significant_features <- biobank_full_analysis_list[FDR_significant_features]

men_residuals <- sapply(significant_features, function(x){x$feature_residuals$value[x$feature_residuals$sex == 1]})

women_residuals <- sapply(significant_features, function(x){x$feature_residuals$value[x$feature_residuals$sex == 0]})
```

```{r factor analysis}
men_residuals_matrix <- matrix(unlist(men_residuals), ncol = length(men_residuals), byrow = F)
names(men_residuals_matrix) = names(men_residuals)

men_factor_analysis <- factanal(men_residuals_matrix,factors = 10)
load <- men_factor_analysis$loadings[,1:10]
plot(load,type="n")
text(load,labels=names(men_residuals_matrix),cex=.7)
```

