---
title: "Correlation analysis v2"
author: "Nitay Alon"
date: "7/17/2019"
output: html_document
---

```{r load methods, include=FALSE}
# local_server_prefix <- "~/Documents/Human_brain_research/DAPHNA_JOEL/"
library(pbapply)
library(corrplot)
local_server_prefix <- "~/Human_brain_research/"
source(paste0(local_server_prefix,"BioBank_data_analysis/New_Analysis_Method/Residuals_analysis_methods/analyze_full_brain_feature.R"))
source(paste0(local_server_prefix,"BioBank_data_analysis/New_Analysis_Method/Residuals_analysis_methods/method_helper.R"))
source(paste0(local_server_prefix,"BioBank_data_analysis/load_biobank_data.R"))
```

```{r load data, include=FALSE}
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/biobank_feature_residual_analysis.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/biobank_feature_standard_analysis.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/combined_df_long_sorted_residuals.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/combined_df_long_sorted_standardize.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/colomns_name.RData")
```

```{r filter FDR significant features, include=FALSE}
sig_level <- 0.01
FDR_significant_features <- rownames(combined_df_long_sorted_residuals)[
    with(combined_df_long_sorted_residuals,(fdr_pv <= sig_level & p < 0.5 & q > 0.5 |
                                  fdr_pv <= sig_level & p > 0.5 & q < 0.5))]  
FDR_significant_features <- na.omit(FDR_significant_features)
```


Partition the data by FA, MD and volume:
```{r order features by names, include=FALSE}
filter_columns_names <- data_set_columns[data_set_columns$V2 %in% FDR_significant_features,]

FA_features <- filter_columns_names$V5[c(grep("mean FA", filter_columns_names$V5),grep("Mean FA", filter_columns_names$V5))]

MD_features <- filter_columns_names$V5[c(grep("mean MD", filter_columns_names$V5),grep("Mean MD", filter_columns_names$V5))]

volume_features <- filter_columns_names$V5[grep("Volume", filter_columns_names$V5)]

features_order <- c(FA_features, MD_features, volume_features)
```

# Residual data

extract feature data:
```{r extract FDR significant features data, include=FALSE}
significant_features <- biobank_feature_residual_analysis[FDR_significant_features]

men_data <- lapply(significant_features, function(x){x$hypothesis_results$pure_type_vs_mixed_gender_em_results$alternative_hypothesis$men_responsebilities})

women_data <- lapply(significant_features, function(x){x$hypothesis_results$pure_type_vs_mixed_gender_em_results$alternative_hypothesis$women_responsebilities})
```

join the tables:
```{r create men table, include=FALSE, warning=FALSE}
men_feature_data <- men_data[[1]]
for(i in 2:length(men_data))
{
  men_feature_data <- base::merge(men_feature_data, men_data[[i]], by.x = "eid", by.y = "eid")
}
names(men_feature_data) <- c("eid", FDR_significant_features)

men_feature_data_ordered <- men_feature_data[names(men_feature_data) %in% filter_columns_names$V2,]
```

```{r create women table, include=FALSE, warning=FALSE}
women_feature_data <- women_data[[1]]
for(i in 2:length(women_data))
{
  women_feature_data <- base::merge(women_feature_data, women_data[[i]], by.x = "eid", by.y = "eid")
}
names(women_feature_data) <- c("eid", FDR_significant_features)

women_feature_data_ordered <- women_feature_data[names(women_feature_data) %in% filter_columns_names$V2,]
```

## Full data correlation data:
```{r full data correlation}
men_cor <- cor(men_feature_data_ordered[,-c(1)], use = "pairwise.complete.obs")
women_cor <- cor(women_feature_data_ordered[,-c(1)],use = "pairwise.complete.obs")

combined_correaltion <- men_cor
combined_correaltion[lower.tri(combined_correaltion)] <- women_cor[lower.tri(women_cor)]

corrplot(combined_correaltion, order="alphabet", title="both genders",
         tl.srt=65, tl.cex=0.95, number.cex=0.8,
         tl.col='red', cl.length = 5, cl.align="l")

par(mfrow = c(2,2))
corrplot(combined_correaltion[1:length(FA_features),1:length(FA_features)], method="color")  
corrplot(combined_correaltion[(length(FA_features) + 1):(length(FA_features) + length(MD_features)),(length(FA_features) + 1):(length(FA_features) + length(MD_features))], method="color")  
corrplot(cormatx[(length(FA_features) + length(MD_features) + 1):12,1:6], method="color")  
corrplot(cormatx[7:12,7:12], method="color") 
```

