---
title: "Hessian computations for significant features"
author: "Nitay Alon"
date: "8/15/2019"
output: html_document
---

In this report we compute the hessian matrix for MLE computed by the EM algorithm in order to compute CI for each parameter.
```{r loadin libraries, include=FALSE}
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/biobank_feature_residual_analysis.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/biobank_feature_standard_analysis.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/BioBank_residual_data.RData")
load("~/Human_brain_research/BioBank_data_analysis/Final_data_for_analysis/BioBank_standardized_data.RData")
```

```{r filter FDR significant features antidiagonal, include=FALSE}
sig_level <- 0.01
FDR_significant_features <- rownames(combined_df_long_sorted_residuals)[
    with(combined_df_long_sorted_residuals,(fdr_pv <= sig_level & 
region == "Anti"))]  
FDR_significant_features <- na.omit(FDR_significant_features)
```


```{r computing the hessian for a given feature, include=FALSE}
fisher_and_more <- pblapply(FDR_significant_features, 
                    function(x){computeFisherMatrixForFeature(biobank_feature_residual_analysis, 
                                          biobank_residuals_data,x)})
```

```{r examine Fisher matrix}
lapply(fisher_and_more, function(x){(eigen(x$fisher))$values})
```

```{r asymptotic std}
lapply(fisher_and_more, function(x){sqrt(diag(solve(x$fisher)))})
```

```{r suspect feature}
FDR_significant_features[[50]]
```

