---
title: "Plotting centers divergance"
author: "Nitay Alon"
date: "10/29/2019"
output: html_document
---

```{r method helper}
computeMeansDiff <- function(bio_bank_feature_data, feature_m_parameters, feature_name){
  #' First see what is the higher mean
  true_sizes <- bio_bank_feature_data[[feature_name]] %>%  
    group_by(sex) %>% 
    summarise(avg = mean(value),
              std = sd(value))
  men_mean = true_sizes$avg[true_sizes$sex == 1]
  women_mean = true_sizes$avg[true_sizes$sex == 0]
  if(men_mean > women_mean){
    masculine = max(feature_m_parameters[[feature_name]]$mu_1,feature_m_parameters[[feature_name]]$mu_2)
    feminine = min(feature_m_parameters[[feature_name]]$mu_1,feature_m_parameters[[feature_name]]$mu_2)
  }else{
    masculine = min(feature_m_parameters[[feature_name]]$mu_1,feature_m_parameters[[feature_name]]$mu_2)
    feminine = max(feature_m_parameters[[feature_name]]$mu_1,feature_m_parameters[[feature_name]]$mu_2)
  }
  return(list(
    data.frame(men_mean = men_mean, women_mean = women_mean, masculine = masculine, feminine = feminine)
  ))
}
```

```{r extract means}
list_of_centres_residuals <- sapply(list.of.names, function(feature_name){
  computeMeansDiff(biobank_residuals_data, feature_residual_m_parameters, feature_name)
})

list_of_centres_log <- sapply(list.of.names, function(feature_name){
  computeMeansDiff(biobank_standardized_data, standardized_data_m_parameters, feature_name)
})
```

```{r compute divergance of means}
residual_plot_data <- sapply(list_of_centres_residuals, function(x){
  c(x$men_mean - x$women_mean,x$masculine - x$feminine)
  })

standard_plot_data <- sapply(list_of_centres_log, function(x){
  c(x$men_mean - x$women_mean,x$masculine - x$feminine)
  })
```

```{r combine with FDR data}
combined_df_long_sorted_standard_with_means <- base::merge(combined_df_long_sorted_standard,t(standard_plot_data),by=0)
combined_df_long_sorted_residuals_with_means <- base::merge(combined_df_long_sorted_residuals,t(residual_plot_data),by=0)
```

```{r plot with same coloring schema as FDR redisuals}
ggplot(combined_df_long_sorted_residuals_with_means[combined_df_long_sorted_residuals_with_means$bins_for_fdr %in% levels(combined_df_long_sorted_residuals_with_means$bins_for_fdr)[c(1,2,3)],], aes(V1 ,V2, colour = region)) +
  geom_point(aes(shape = bins_for_fdr)) +
  scale_shape_manual(values=c(3, 6))+
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  ggtitle("Distance between empirical and theretical centers", subtitle = "Shape indicate FDR pv") + 
  xlab("Men - Women") + 
  ylab("Masculine - Feminine")
```

```{r r plot with same coloring schema as FDR standardize}
ggplot(combined_df_long_sorted_standard_with_means[combined_df_long_sorted_standard_with_means$bins_for_fdr %in% levels(combined_df_long_sorted_standard_with_means$bins_for_fdr)[c(1,2,3)],], aes(V1 ,V2, colour = region)) +
  geom_point(aes(shape = bins_for_fdr)) +
  scale_shape_manual(values=c(3, 6, 18))+
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  ggtitle("Distance between empirical and theretical centers", subtitle = "Shape indicate FDR pv") + 
  xlab("Men - Women") + 
  ylab("Masculine - Feminine")
```

# Post October 2019 meeting analysis

Following Daphy and Isaco's meeting, a post analysis of the features is required. Focusing our intention to the features that lay in the intersection of the lines in the last plot.
```{r extract zero distacne features}
zero_diff_features_names <- combined_df_long_sorted_standard_with_means[abs(combined_df_long_sorted_standard_with_means$V1 - combined_df_long_sorted_standard_with_means$V2) < 0.1 &
                                              abs(combined_df_long_sorted_standard_with_means$V1) < 0.1,]$Row.names

combined_df_long_sorted_standard_with_means[combined_df_long_sorted_standard_with_means$Row.names == zero_diff_features_names[2],]
```

Examining these features:
```{r examine zero center diff features}
biobank_feature_standard_analysis[[zero_diff_features_names[1]]]$hypothesis_results$pure_type_vs_mixed_gender_em_results$alternative_hypothesis$m_parameters
standardized_data_m_parameters[[zero_diff_features_names[1]]]

list_of_centres_log[[zero_diff_features_names[2]]]

biobank_feature_standard_analysis[[zero_diff_features_names[2]]]$hypothesis_results$pure_type_vs_mixed_gender_em_results$alternative_hypothesis$m_parameters
standardized_data_m_parameters[[zero_diff_features_names[2]]]

biobank_standardized_data[[zero_diff_features_names[2]]] %>% 
  group_by(sex) %>% 
    summarise(avg = mean(value),
              std = sd(value))


biobank_feature_standard_analysis[[zero_diff_features_names[3]]]$hypothesis_results$pure_type_vs_mixed_gender_em_results$alternative_hypothesis$m_parameters
```

