---
title: "export tables for daphy"
author: "Nitay Alon"
date: "12/22/2019"
output: html_document
---

# Export tables
For each cohort - pure types, single mixture model, two-mixture model in Q1+Q3 and mosaic features (Q2+Q4) we export the following table: name, q, p, Cohen-d, t-test value
```{r load required libraries, warning=FALSE}
library(dplyr)
library(RColorBrewer)
library(magrittr)
library(ggplot2)
```

## Pure types table

```{r extract t test pv}
pure_types_t_test_data <- sapply(biobank_feature_residual_analysis[rownames(pure_types_residual_model_table)], function(x){x$`hypothesis_results`$`t_test_for_difference_between_genders`$`p.value`}) %>% data.frame()
pure_types_cohen_d_data <- sapply(biobank_feature_residual_analysis[rownames(pure_types_residual_model_table)], function(x){x$`hypothesis_results`$`cohen_d_test`$`estimate`}) %>% data.frame()

pure_types_t_test_data$`Region.name` <- rownames(pure_types_t_test_data)
pure_types_residual_model_table$`Region.name` <- rownames(pure_types_residual_model_table)

pure_types_residual_data_with_t_test <- base::merge(pure_types_residual_model_table,
                                  pure_types_t_test_data, by.x = 'Region.name', by.y = 'Region.name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))
names(pure_types_residual_data_with_t_test)[ncol(pure_types_residual_data_with_t_test)] <- 't_test_p_value'
pure_types_residual_data_with_t_test$adjusted_pv <- p.adjust(pure_types_residual_data_with_t_test$t_test_p_value, method = 'BH')

pure_types_residual_data_with_t_test_and_correlation_matrix_location <- 
  base::merge(pure_types_residual_data_with_t_test,
                                  pure_type_correlation_plot_legend, by.x = 'Region.name', by.y = 'feature_name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))

pure_types_residual_data_with_t_test_and_correlation_matrix_location %>% 
select(Region.name, p,q,Cohen_D,fdr_pv, adjusted_pv,number) %>% 
write.csv(., file = "~/Human_brain_research/data_for_paper/pure_types_features_residual_data.csv", row.names = T)
```

## Single mixture model

```{r single mixture model table, warning=FALSE}
equal_probability_mixture_names <- combined_df_resid_equal_probs_sorted$feature[combined_df_resid_equal_probs_sorted$bh_pvalue > 0.05]

equal_mixture_model_types_residual_table <- combined_df_resid_equal_probs_sorted %>% 
  filter(feature %in% equal_probability_mixture_names)

single_mixture_model_t_test_data <- sapply(biobank_feature_residual_analysis[equal_mixture_model_types_residual_table$feature], function(x){x$`hypothesis_results`$`t_test_for_difference_between_genders`$`p.value`}) %>% data.frame()
single_mixture_model_cohen_d_data <- sapply(biobank_feature_residual_analysis[equal_probability_mixture_names], function(x){x$`hypothesis_results`$`cohen_d_test`$`estimate`}) %>% data.frame()

single_mixture_model_t_test_data$`Region.name` <- rownames(single_mixture_model_t_test_data)
single_mixture_model_cohen_d_data$`Region.name` <- rownames(single_mixture_model_t_test_data)


single_mixture_model_residual_data_with_t_test <- base::merge(equal_mixture_model_types_residual_table,
                                  single_mixture_model_t_test_data, by.x = 'feature', by.y = 'Region.name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))

names(single_mixture_model_residual_data_with_t_test)[ncol(single_mixture_model_residual_data_with_t_test)] <- 't_test_p_value'

single_mixture_model_residual_data_with_t_test$adjusted_pv <- p.adjust(single_mixture_model_residual_data_with_t_test$t_test_p_value, method = 'BH')

single_mixture_model_residual_data_with_t_test_and_correlation_matrix_location <- 
  base::merge(single_mixture_model_residual_data_with_t_test,
                                  single_mixture_model_correlation_plot_legend, by.x = 'feature', by.y = 'feature_name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))

single_mixture_model_residual_data_with_t_test_and_correlation_matrix_location %>% 
select(feature, p,q,Cohen_D,fdr_pv, adjusted_pv,number) %>% 
write.csv(., file = "~/Human_brain_research/data_for_paper/single_mixture_model_residual_data_with_t_test.csv", row.names = T)
```

## Two mixture model Q1,Q3

```{r separate mixture model data to quadrants}
non_equal_mixture_model_types_residual_table_q1_q3 <- combined_df_resid_equal_probs_sorted[combined_df_resid_equal_probs_sorted$feature %in% q1_and_q3_features,]

non_equal_mixture_model_types_residual_table_q2_q4 <- combined_df_resid_equal_probs_sorted[combined_df_resid_equal_probs_sorted$feature %in% q2_q4_features_names,]
```

```{r extract t test data q1 q3}
q1_q3_mixture_model_t_test_data <- sapply(biobank_feature_residual_analysis[non_equal_mixture_model_types_residual_table_q1_q3$feature], function(x){x$`hypothesis_results`$`t_test_for_difference_between_genders`$`p.value`}) %>% data.frame()

q1_q3_mixture_model_cohen_d <- sapply(biobank_feature_residual_analysis[non_equal_mixture_model_types_residual_table_q1_q3$feature], function(x){x$`hypothesis_results`$`cohen_d_test`$`estimate`}) %>% data.frame()

q1_q3_mixture_model_t_test_data$`Region.name` <- rownames(q1_q3_mixture_model_t_test_data)
q1_q3_mixture_model_cohen_d$`Region.name` <- rownames(q1_q3_mixture_model_t_test_data)

q1_q3_mixture_model_residual_data_with_t_test <- base::merge(non_equal_mixture_model_types_residual_table_q1_q3,
                                  q1_q3_mixture_model_t_test_data, by.x = 'feature', by.y = 'Region.name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))

names(q1_q3_mixture_model_residual_data_with_t_test)[ncol(q1_q3_mixture_model_residual_data_with_t_test)] <- 't_test_p_value'
q1_q3_mixture_model_residual_data_with_t_test$adjusted_pv <- p.adjust(q1_q3_mixture_model_residual_data_with_t_test$t_test_p_value, method = 'BH')

q1_q3_mixture_model_residual_data_with_t_test_and_correlation_matrix_location <- 
  base::merge(q1_q3_mixture_model_residual_data_with_t_test,
                                  q1_q3_mixture_model_correlation_plot_legend, by.x = 'feature', by.y = 'feature_name',
                                  all = TRUE)

q1_q3_mixture_model_residual_data_with_t_test_and_correlation_matrix_location %>% 
select(feature, p,q,Cohen_D,fdr_pv, adjusted_pv, number) %>% 
write.csv(., file = "~/Human_brain_research/data_for_paper/q1_q3_mixture_model_residual_data_with_t_test.csv", row.names = T)
```

```{r extract t test data q2 q4}
q2_q4_mixture_model_t_test_data <- sapply(biobank_feature_residual_analysis[non_equal_mixture_model_types_residual_table_q2_q4$feature], function(x){x$`hypothesis_results`$`t_test_for_difference_between_genders`$`p.value`}) %>% data.frame()
q2_q4_mixture_model_cohen_d <- sapply(biobank_feature_residual_analysis[non_equal_mixture_model_types_residual_table_q2_q4$feature], function(x){x$`hypothesis_results`$`cohen_d_test`$`estimate`}) %>% data.frame()


q2_q4_mixture_model_t_test_data$`Region.name` <- rownames(q2_q4_mixture_model_t_test_data)
q2_q4_mixture_model_cohen_d$`Region.name` <- rownames(q2_q4_mixture_model_cohen_d)

q2_q4_mixture_model_residual_data_with_t_test <- base::merge(non_equal_mixture_model_types_residual_table_q2_q4,
                                  q2_q4_mixture_model_t_test_data, by.x = 'feature', by.y = 'Region.name',
                                  all = TRUE, suffix = c(".mixture_model",".t_test"))

names(q2_q4_mixture_model_residual_data_with_t_test)[ncol(q2_q4_mixture_model_residual_data_with_t_test)] <- 't_test_p_value'
q2_q4_mixture_model_residual_data_with_t_test$adjusted_pv <- p.adjust(q2_q4_mixture_model_residual_data_with_t_test$t_test_p_value, method = 'BH')

q2_q4_mixture_model_residual_data_with_t_test_and_correlation_matrix_location <- 
  base::merge(q2_q4_mixture_model_residual_data_with_t_test,
                                  q2_q4_mixture_model_correlation_plot_legend, by.x = 'feature', by.y = 'feature_name',
                                  all = TRUE)

q2_q4_mixture_model_residual_data_with_t_test_and_correlation_matrix_location %>% 
select(feature, p,q,Cohen_D,fdr_pv, adjusted_pv, number) %>% 
write.csv(., file = "~/Human_brain_research/data_for_paper/q2_q4_mixture_model_residual_data_with_t_test.csv", row.names = T)
```

# Legacy
```{r log data pure types, warning=FALSE}
pure_types_residual_model_log_table <- 
combined_df_long_sorted_standard[combined_df_long_sorted_standard$bins_for_fdr %in% levels(combined_df_long_sorted_standard$bins_for_fdr)[c(3,4)],] %>% 
  select(p_values, p, q, Cohen_D) 

log_volume_data_for_residual_pure_type <- 
combined_df_long_sorted_standard[rownames(combined_df_long_sorted_standard) %in% 
                                   rownames(pure_types_residual_model_residual_table),] %>% 
  select(p_values, p, q, Cohen_D) 

pure_types_residual_model_residual_table <- sapply(pure_types_residual_model_residual_data, function(x){
  c(x$mixture_model$m_parameters$p,
    x$mixture_model$m_parameters$q,
    x$hypothesis_results$cohen_d_test$estimate)
})

pure_types_residual_data <- base::merge(pure_types_residual_model_residual_table,
                                  log_volume_data_for_residual_pure_type, by = 0,
                                  all = TRUE,
                                  suffixes = c(".residual",".log"))
```

```{r non significant log features table, warning=FALSE}
pure_types_log_model_log_table <- 
combined_df_long_sorted_standard[combined_df_long_sorted_standard$bins_for_fdr %in% levels(combined_df_long_sorted_standard$bins_for_fdr)[c(3,4)],] %>% 
  select(p_values, p, q, Cohen_D) 

pure_types_log_model_residual_table <- 
combined_df_long_sorted_residuals[rownames(pure_types_log_model_log_table),] %>% 
  select(p_values, p, q, Cohen_D) 

pure_types_log_data <- base::merge(pure_types_log_model_log_table,
                                  pure_types_log_model_residual_table, by = 0,
                                  all = TRUE,
                                  suffixes = c(".log",".residual"))

t_test_data_log_data <- sapply(biobank_feature_standard_analysis[rownames(pure_types_log_model_log_table)], function(x){x$`hypothesis_results`$`t_test_for_difference_between_genders`$`p.value`}) %>% data.frame()

t_test_data_log_data$`Row.names` <- rownames(t_test_data_log_data)
pure_types_log_data_with_t_test <- base::merge(pure_types_log_data,
                                  t_test_data_log_data, 
                                  by.x = 'Row.names', by.y='Row.names',
                                  all = TRUE)
names(pure_types_log_data_with_t_test)[ncol(pure_types_log_data_with_t_test)] <- 't_test_p_value'
pure_types_log_data_with_t_test$adjusted_pv <- p.adjust(pure_types_log_data_with_t_test$t_test_p_value, method = 'BH')

write.csv(pure_types_log_data_with_t_test, file = "pure_types_features_log_data.csv", row.names = T)
```


# Plots 

```{r selecting features for each analysis}
pure_types_volume_features <- pure_types_features_names[pure_types_features_names %>% grep("Volume", .)]

single_mixture_model_volume_features <- equal_probability_mixture_names[equal_probability_mixture_names %>% grep("Volume",.)]

two_mixture_model_volume_features <- non_equal_probability_mixture_names[non_equal_probability_mixture_names %>% grep("Volume",.)]
```


```{r full mixture model histograms}
i <- which(non_equal_probability_mixture_names == 'Volume of grey matter in Lingual Gyrus (left)')

plotGenderHistogram(biobank_standardized_data[[non_equal_probability_mixture_names[i]]],
  biobank_feature_standard_analysis[[non_equal_probability_mixture_names[i]]], non_equal_probability_mixture_names[i])

plotGenderHistogram(biobank_residuals_data[[non_equal_probability_mixture_names[i]]],
  biobank_feature_residual_analysis[[non_equal_probability_mixture_names[i]]], non_equal_probability_mixture_names[i])
```

```{r single mixture model histograms}
i <- which(single_mixture_model_volume_features == "Volume of grey matter in Occipital Fusiform Gyrus (left)")
plotGenderHistogram(biobank_standardized_data[[single_mixture_model_volume_features[i]]],
  biobank_feature_standard_analysis[[single_mixture_model_volume_features[i]]], 
  single_mixture_model_volume_features[i])

plotGenderHistogram(biobank_residuals_data[[single_mixture_model_volume_features[i]]],
  biobank_feature_residual_analysis[[single_mixture_model_volume_features[i]]], 
  single_mixture_model_volume_features[i])
```


```{r residual pure type with log data}
i <- which(pure_types_features_names == "Volume of grey matter in Postcentral Gyrus (left)")
plotGenderHistogram(biobank_standardized_data[[pure_types_features_names[i]]],
  biobank_feature_standard_analysis[[pure_types_features_names[i]]], pure_types_features_names[i],F)

plotGenderHistogram(biobank_residuals_data[[pure_types_features_names[i]]],
  biobank_feature_residual_analysis[[pure_types_features_names[i]]], pure_types_features_names[i],two_mixtures = F)
```

Plotting 2 features side by side to see the mosiac 
```{r scatter plot of two features}
str(biobank_standardized_data[[volume_features_for_plot[1]]])
str(biobank_standardized_data[[volume_features_for_plot[2]]])
```

```{r correlation validation}
inner_join(biobank_standardized_data[[volume_features_for_plot[1]]],
        biobank_standardized_data[[volume_features_for_plot[2]]],
     by = 'eid') %>% 
  select(value.x, value.y) %>% 
  cor()
```


```{r scatter plot log volume}
i <- 1
j <- 2
inner_join(biobank_standardized_data[[volume_features_for_plot[i]]],
        biobank_standardized_data[[volume_features_for_plot[j]]],
     by = 'eid') %>% 
  select(value.x, value.y, sex = sex.x) %>% 
  mutate(sex = factor(sex)) %>% 
ggplot(aes(value.x, value.y,color = sex)) + 
  geom_point(shape=20, size = 1, alpha = 1/2) +
  ggtitle("Volume") + 
  xlab(sprintf(volume_features_for_plot[1])) + 
  ylab(sprintf(volume_features_for_plot[5])) +
  coord_fixed() 
```

```{r scatter plot residuals}
inner_join(biobank_residuals_data[[volume_features_for_plot[i]]],
        biobank_residuals_data[[volume_features_for_plot[j]]],
     by = 'eid') %>% 
  select(value.x, value.y, sex = sex.x) %>% 
  mutate(sex = factor(sex)) %>% 
ggplot(aes(value.x, value.y,color = sex)) + 
  geom_point(shape=20, size = 1, alpha = 1/2) +
  ggtitle("Volume") + 
  xlab(sprintf(volume_features_for_plot[1])) + 
  ylab(sprintf(volume_features_for_plot[5])) +
  coord_fixed() 
```

```{r scatter plot two probabilities}
scatter_plot_two_probabilities <- cbind(
rbind(inner_join(biobank_residuals_data[[volume_features_for_plot[i]]],
        biobank_residuals_data[[volume_features_for_plot[j]]],
     by = 'eid'),
     inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[i]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[j]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid')), c(rep(0,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[i]]]$hypothesis_results$mixture_model$women_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[j]]]$hypothesis_results$mixture_model$women_responsebilities,
     by = 'eid'))), sex = rep(1,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[1]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[j]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid'))))) %>% data.frame()
names(scatter_plot_two_probabilities) = c('eid','responsebility.x', 'responsebility.y', 'sex')

ggplot(scatter_plot_two_probabilities, aes(responsebility.x, responsebility.y, col = factor(sex))) + 
  geom_point(shape=20, size = 1) + 
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) 
```

```{r scatter plot}
inner_join(biobank_standardized_data[[volume_features_for_plot[1]]],
        biobank_standardized_data[[volume_features_for_plot[2]]],
     by = 'eid') %>% 
  select(value.x, value.y, sex = sex.x) %>% 
  mutate(sex = factor(sex)) %>% 
ggplot(aes(value.x, value.y,color = sex)) + 
  geom_point(shape=1, size = 1) +
  ggtitle("Volume") + 
  xlab(sprintf(volume_features_for_plot[1])) + 
  ylab(sprintf(volume_features_for_plot[2])) +
  coord_fixed() 

```

```{r scatter plot two probabilities}
scatter_plot_two_probabilities <- cbind(
rbind(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[1]]]$hypothesis_results$mixture_model$women_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$women_responsebilities,
     by = 'eid'),
     inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[1]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid')), c(rep(0,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[1]]]$hypothesis_results$mixture_model$women_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$women_responsebilities,
     by = 'eid'))), sex = rep(1,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[1]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid'))))) %>% data.frame()
names(scatter_plot_two_probabilities) = c('eid','responsebility.x', 'responsebility.y', 'sex')

ggplot(scatter_plot_two_probabilities, aes(responsebility.x, responsebility.y, col = factor(sex))) + 
  geom_point(shape=1, size = 1) + 
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) 
```


```{r scatter plot}
inner_join(biobank_standardized_data[[volume_features_for_plot[2]]],
        biobank_standardized_data[[volume_features_for_plot[5]]],
     by = 'eid') %>% 
  select(value.x, value.y, sex = sex.x) %>% 
  mutate(sex = factor(sex)) %>% 
ggplot(aes(value.x, value.y,color = sex)) + 
  geom_point(shape=1, size = 1) +
  ggtitle("Volume") + 
  xlab(sprintf(volume_features_for_plot[2])) + 
  ylab(sprintf(volume_features_for_plot[5])) +
  coord_fixed() 

```


```{r scatter plot two probabilities}
scatter_plot_two_probabilities <- cbind(
rbind(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[5]]]$hypothesis_results$mixture_model$women_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$women_responsebilities,
     by = 'eid'),
     inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[5]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid')), c(rep(0,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[5]]]$hypothesis_results$mixture_model$women_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$women_responsebilities,
     by = 'eid'))), sex = rep(1,nrow(inner_join(biobank_feature_residual_analysis[[volume_features_for_plot[5]]]$hypothesis_results$mixture_model$men_responsebilities,
        biobank_feature_residual_analysis[[volume_features_for_plot[2]]]$hypothesis_results$mixture_model$men_responsebilities,
     by = 'eid'))))) %>% data.frame()
names(scatter_plot_two_probabilities) = c('eid','responsebility.x', 'responsebility.y', 'sex')

ggplot(scatter_plot_two_probabilities, aes(responsebility.x, responsebility.y, col = factor(sex))) + 
  geom_point(shape=1, size = 1) + 
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) 
```


```{r}
df_p_vs_q <- combined_df_resid_equal_probs_sorted %>% 
  select(p,q,Cohen_D,p_equal_q) %>% 
  mutate(bins_for_cohen_d = cut(Cohen_D, c(-0.3,-0.2,-0.1, 0.1, 0.2, 0.3,0.4))) 

ggplot(df_p_vs_q, aes(p,q)) +
  geom_point(aes(colour = bins_for_cohen_d,shape = p_equal_q)) +
  scale_shape_manual(values=c(3, 19))+
  geom_vline(xintercept = 0.5) +
  geom_hline(yintercept = 0.5) +
  ggtitle("Values of p and q", subtitle = "shape is p=q hypothesis") + 
  geom_abline(slope = 1, intercept = 0) + 
  scale_color_manual(name = "Cohen D",
                     values = c("(-0.3,-0.2]" = "red4",
                                "(-0.2,-0.1]" = "red1",
                                "(-0.1,0.1]" = "orange1",
                                "(0.1,0.2]" = "deepskyblue1",
                                "(0.2,0.3]" = "dodgerblue1",
                                "(0.3,0.4]" = "dodgerblue2"),
                     labels = c("<-0.2","0.2<=d<-0.1","-0.1<=d<0.1","0.1<=d<0.2","0.2<=d<3","0.3<=d<0.4")) +
  theme_bw() + 
  theme(axis.text.x = element_text(face="bold", color="black", 
                           size=7),
          axis.text.y = element_text(face="bold", color="black", 
                           size=7))
```

```{r Cohen's d analysis}
combined_df_resid_equal_probs_sorted %>% 
  summarise(min = min(Cohen_D), max = max(Cohen_D), avg = mean(Cohen_D))
```

```{r probability ratio analysis q2 q2}
combined_df_resid_equal_probs_sorted %>% 
  filter(feature %in% q2_q4_features_names) %>% 
  mutate(women_to_women_ratio = q*q + (1-q)*(1-q),
         men_to_men_ratio = p*p + (1-p)*(1-p),
         men_to_women_ratio = p*q + (1-p)*(1-q)) %>% 
  select(feature,women_to_women_ratio,men_to_men_ratio,men_to_women_ratio) %>% 
  mutate(ratio_to_two_women = men_to_women_ratio / women_to_women_ratio,
         ratio_to_two_men = men_to_women_ratio / men_to_men_ratio) %>% 
  summarise(min_ratio_to_two_women = min(ratio_to_two_women), 
            max_ratio_to_two_women = max(ratio_to_two_women),
            avg_ratio_to_two_women = mean(ratio_to_two_women))
```
```{r probability ratio analysis q1 q3}
combined_df_resid_equal_probs_sorted %>% 
  filter(feature %in% q1_and_q3_features) %>% 
  mutate(women_to_women_ratio = q*q + (1-q)*(1-q),
         men_to_men_ratio = p*p + (1-p)*(1-p),
         men_to_women_ratio = p*q + (1-p)*(1-q)) %>% 
  select(feature,women_to_women_ratio,men_to_men_ratio,men_to_women_ratio) %>% 
  mutate(ratio_to_two_women = men_to_women_ratio / women_to_women_ratio,
         ratio_to_two_men = men_to_women_ratio / men_to_men_ratio) %>% 
  summarise(min_ratio_to_two_women = min(ratio_to_two_women), 
            max_ratio_to_two_women = max(ratio_to_two_women),
            avg_ratio_to_two_women = mean(ratio_to_two_women),
            min_ratio_to_two_men = min(ratio_to_two_men), 
            max_ratio_to_two_men = max(ratio_to_two_men),
            avg_ratio_to_two_men = mean(ratio_to_two_men))
```
```{r probability ratio analysis p equal q}
single_mixture_model_features %>% 
  mutate(women_to_women_ratio = q*q + (1-q)*(1-q),
         men_to_men_ratio = p*p + (1-p)*(1-p),
         men_to_women_ratio = p*q + (1-p)*(1-q)) %>% 
  select(feature,women_to_women_ratio,men_to_men_ratio,men_to_women_ratio) %>% 
  mutate(ratio_to_two_women = men_to_women_ratio / women_to_women_ratio,
         ratio_to_two_men = men_to_women_ratio / men_to_men_ratio) %>% 
  summarise(min_ratio_to_two_women = min(ratio_to_two_women), 
            max_ratio_to_two_women = max(ratio_to_two_women),
            avg_ratio_to_two_women = mean(ratio_to_two_women),
            min_ratio_to_two_men = min(ratio_to_two_men), 
            max_ratio_to_two_men = max(ratio_to_two_men),
            avg_ratio_to_two_men = mean(ratio_to_two_men))
```


