# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EM <- function(men_data, women_data, number_of_iterations, p, q, mu_1, mu_2, sigma_2_men, sigma_2_women) {
    .Call('_HumanBrainMosaic_EM', PACKAGE = 'HumanBrainMosaic', men_data, women_data, number_of_iterations, p, q, mu_1, mu_2, sigma_2_men, sigma_2_women)
}

