// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EM
List EM(NumericVector men_data, NumericVector women_data, int number_of_iterations, double p, double q, double mu_1, double mu_2, double sigma_2_men, double sigma_2_women);
RcppExport SEXP _HumanBrainMosaic_EM(SEXP men_dataSEXP, SEXP women_dataSEXP, SEXP number_of_iterationsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP mu_1SEXP, SEXP mu_2SEXP, SEXP sigma_2_menSEXP, SEXP sigma_2_womenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type men_data(men_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type women_data(women_dataSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_iterations(number_of_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu_1(mu_1SEXP);
    Rcpp::traits::input_parameter< double >::type mu_2(mu_2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma_2_men(sigma_2_menSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_2_women(sigma_2_womenSEXP);
    rcpp_result_gen = Rcpp::wrap(EM(men_data, women_data, number_of_iterations, p, q, mu_1, mu_2, sigma_2_men, sigma_2_women));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HumanBrainMosaic_EM", (DL_FUNC) &_HumanBrainMosaic_EM, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_HumanBrainMosaic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
