// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EM
NumericVector EM(NumericVector men_data, NumericVector women_data);
RcppExport SEXP _HumanBrainMosaic_EM(SEXP men_dataSEXP, SEXP women_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type men_data(men_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type women_data(women_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(EM(men_data, women_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HumanBrainMosaic_EM", (DL_FUNC) &_HumanBrainMosaic_EM, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_HumanBrainMosaic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
